apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacapstone
  labels:
    app: udacapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacapstone
    spec:
      containers:
        - image: kuldeeprana/udacapstone
          imagePullPolicy: Always
          name: udacapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacapstone
  labels:
    app: udacapstone
spec:
  type: LoadBalancer
  selector:
    app: udacapstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
